CREATE INDEX REC_CHG_IDX ON CM_REC_CHG(SOURCE_ID) LOCAL PARALLEL;
ALTER INDEX REC_CHG_IDX NOPARALLEL;

CREATE INDEX BILL_ITEM_IDX ON CM_MISC_BILL_ITEM(SUB_ACCT) LOCAL PARALLEL;
ALTER INDEX BILL_ITEM_IDX NOPARALLEL;