ALTER TABLE CM_REC_CHG ADD
    (DIVISION      CHAR(5)        NOT NULL ENABLE,
    SUB_ACCT       VARCHAR2(15)   NOT NULL ENABLE,
    ACCOUNT_ID     CHAR(10)       NOT NULL ENABLE,
    SUB_ACCOUNT_ID CHAR(10)       NOT NULL ENABLE);