CREATE TABLE cm_rec_idfr (
    SOURCE_ID      VARCHAR2(15)
        NOT NULL ENABLE,
    CUTOFF_DT      DATE,
    FREQUENCY_ID   VARCHAR2(15),
    ILM_DT         TIMESTAMP
        NOT NULL ENABLE,
    BATCH_CODE     VARCHAR2(128)
        NOT NULL ENABLE,
    BATCH_ATTEMPT        NUMBER(3, 0)
        NOT NULL ENABLE,
    CRE_DTTM         TIMESTAMP            NOT NULL ENABLE,
    PARTITION_ID NUMBER(*,0) NOT NULL ENABLE,
    PARTITION        NUMBER(5,0)          GENERATED ALWAYS AS (ORA_HASH(source_id, 15)) VIRTUAL
)
TABLESPACE CBE_CUE_DATA
    PARTITION BY RANGE (ilm_dt) INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY LIST(PARTITION)
SUBPARTITION TEMPLATE(
    SUBPARTITION p1 VALUES(0,1,2,3),
    SUBPARTITION p2 VALUES(4,5,6,7),
    SUBPARTITION p3 VALUES(8,9,10,11),
    SUBPARTITION p4 VALUES(12,13,14,15)
)
(PARTITION before_2020 VALUES LESS THAN (TO_DATE('01-JAN-2020', 'dd-MON-yyyy')))
ENABLE ROW MOVEMENT;
