create table CM_REC_CHG_AUDIT
(
   "REC_CHG_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"PRODUCT_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"LCP" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"PARTY_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"FREQUENCY_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"CURRENCY_CD" CHAR(3 BYTE) NOT NULL ENABLE,
	"PRICE" NUMBER(36,18) NOT NULL ENABLE,
	"QUANTITY" NUMBER(36,0) NOT NULL ENABLE,
	"VALID_FROM" DATE NOT NULL ENABLE,
	"VALID_TO" DATE,
	"STATUS" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"SOURCE_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"CRE_DTTM" DATE NOT NULL ENABLE,
	"LAST_UPD_DTTM" DATE NOT NULL ENABLE,
	"BATCH_CODE" VARCHAR2(128 BYTE) NOT NULL ENABLE,
	"BATCH_ATTEMPT" NUMBER(3,0) NOT NULL ENABLE,
	"PARTITION_ID" NUMBER(*,0) NOT NULL ENABLE,
	"ILM_DT" DATE NOT NULL ENABLE,
	"ILM_ARCH_SW" CHAR(1 BYTE) NOT NULL ENABLE,
	"DIVISION" CHAR(5 BYTE) NOT NULL ENABLE,
	"SUB_ACCT" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"ACCOUNT_ID" CHAR(10 BYTE) NOT NULL ENABLE,
	"SUB_ACCOUNT_ID" CHAR(10 BYTE) NOT NULL ENABLE,
	"TXN_HEADER_ID" CHAR(14 BYTE) NOT NULL ENABLE,
   CONSTRAINT "CM_REC_CHG_PK_AUDIT" PRIMARY KEY ("REC_CHG_ID")
)
TABLESPACE CBE_CUE_DATA
    PARTITION BY RANGE (ilm_dt) INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY hash(batch_code, batch_attempt, partition_id) SUBPARTITIONS 16 (
  PARTITION before_2000 VALUES LESS THAN (TO_DATE('01-JAN-2000', 'dd-MON-yyyy'))
);