create table CM_MISC_BILL_ITEM_LN
(
    BILL_ITEM_LINE_ID VARCHAR2(15)   NOT NULL ENABLE,
    BILL_ITEM_ID      VARCHAR2(12)   NOT NULL ENABLE,
    LINE_CALC_TYPE    VARCHAR2(8)    NOT NULL ENABLE,
    AMOUNT            NUMBER(36, 18) NOT NULL ENABLE,
    CRE_DTTM          DATE           NOT NULL ENABLE,
    ILM_DTTM          DATE           NOT NULL ENABLE,
    ILM_ARCH_SW       CHAR(1)        NOT NULL ENABLE,
    BATCH_CD          VARCHAR2(128)  NOT NULL ENABLE
);
