ALTER TABLE CM_MISC_BILL_ITEM
ADD CONSTRAINT misc_bill_item_pk PRIMARY KEY (MISC_BILL_ITEM_ID);

ALTER TABLE CM_MISC_BILL_ITEM_LN
ADD CONSTRAINT misc_bill_item_ln_pk PRIMARY KEY (BILL_ITEM_LINE_ID, BILL_ITEM_ID);
