create table CM_MISC_BILL_ITEM_LN
(
    BILL_ITEM_LINE_ID VARCHAR2(15)   NOT NULL ENABLE,
    BILL_ITEM_ID      VARCHAR2(12)   NOT NULL ENABLE,
    LINE_CALC_TYPE    VARCHAR2(8)    NOT NULL ENABLE,
    AMOUNT            NUMBER(36, 18) NOT NULL ENABLE,
    CRE_DTTM          DATE           NOT NULL ENABLE,
    BATCH_CODE        VARCHAR2(128)  NOT NULL ENABLE,
    BATCH_ATTEMPT     NUMBER(3, 0)   NOT NULL ENABLE,
    PARTITION_ID      INTEGER        NOT NULL ENABLE,
    ILM_DT            DATE           NOT NULL ENABLE,
    ILM_ARCH_SW       CHAR(1)        NOT NULL ENABLE
)
TABLESPACE CBE_CUE_DATA
    PARTITION BY RANGE (ilm_dt) INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY hash(batch_code, batch_attempt, partition_id) SUBPARTITIONS 16 (
  PARTITION before_2000 VALUES LESS THAN (TO_DATE('01-JAN-2000', 'dd-MON-yyyy'))
);
