ALTER TABLE CM_MISC_BILL_ITEM ADD
    ( DIVISION          CHAR(5)       NOT NULL ENABLE,
    ACCOUNT_ID          CHAR(10)      NOT NULL ENABLE,
    SUB_ACCOUNT_ID      CHAR(10)      NOT NULL ENABLE );

