ALTER TABLE CM_REC_CHG MODIFY (FREQUENCY_ID NULL, PRICE NULL);
ALTER TABLE CM_REC_CHG_AUDIT MODIFY (FREQUENCY_ID NULL, PRICE NULL);
ALTER TABLE CM_REC_CHG MODIFY (CURRENCY_CD NULL);
ALTER TABLE CM_REC_CHG_AUDIT MODIFY (CURRENCY_CD NULL);

