ALTER TABLE CM_REC_CHG MODIFY (FREQUENCY_ID NOT NULL, PRICE NOT NULL);
ALTER TABLE CM_REC_CHG_AUDIT MODIFY (FREQUENCY_ID NOT NULL, PRICE NOT NULL);
ALTER TABLE CM_REC_CHG MODIFY (CURRENCY_CD NOT NULL);
ALTER TABLE CM_REC_CHG_AUDIT MODIFY (CURRENCY_CD NOT NULL);

