create table CM_REC_CHG
(
    REC_CHG_ID    VARCHAR2(15)   NOT NULL ENABLE,
    PRODUCT_ID    VARCHAR2(30)   NOT NULL ENABLE,
    LCP           VARCHAR2(30)   NOT NULL ENABLE,
    PARTY_ID      VARCHAR2(30)   NOT NULL ENABLE,
    FREQUENCY_ID  VARCHAR2(15)   NOT NULL ENABLE,
    CURRENCY_CD   CHAR(3)        NOT NULL ENABLE,
    PRICE         NUMBER(36, 18) NOT NULL ENABLE,
    QUANTITY      NUMBER(36)     NOT NULL ENABLE,
    VALID_FROM    DATE           NOT NULL ENABLE,
    VALID_TO      DATE,
    STATUS        VARCHAR2(15)   NOT NULL ENABLE,
    SOURCE_ID     VARCHAR2(15)   NOT NULL ENABLE,
    CRE_DTTM      DATE           NOT NULL ENABLE,
    LAST_UPD_DTTM DATE           NOT NULL ENABLE,
    BATCH_CODE    VARCHAR2(128)  NOT NULL ENABLE,
    BATCH_ATTEMPT NUMBER(3, 0)   NOT NULL ENABLE,
    PARTITION_ID  INTEGER        NOT NULL ENABLE,
    ILM_DT        DATE           NOT NULL ENABLE,
    ILM_ARCH_SW   CHAR(1)        NOT NULL ENABLE
)
TABLESPACE CBE_CUE_DATA
    PARTITION BY RANGE (ilm_dt) INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY hash(batch_code, batch_attempt, partition_id) SUBPARTITIONS 16 (
  PARTITION before_2000 VALUES LESS THAN (TO_DATE('01-JAN-2000', 'dd-MON-yyyy'))
);
