CREATE INDEX REC_CHG_SRC_IDX ON CM_REC_CHG(SOURCE_ID) LOCAL PARALLEL 16;
ALTER INDEX REC_CHG_SRC_IDX NOPARALLEL;

CREATE INDEX BILL_ITEM_SUB_ACCT_SRC_IDX ON CM_MISC_BILL_ITEM(SUB_ACCT, SOURCE_ID) LOCAL PARALLEL 16;
ALTER INDEX BILL_ITEM_SUB_ACCT_SRC_IDX NOPARALLEL;