Insert into CM_BCHG_STG
(TXN_HEADER_ID  ,  UPLOAD_DTTM  ,  BO_STATUS_CD  ,  STATUS_UPD_DTTM  ,  MESSAGE_CAT_NBR  ,
MESSAGE_NBR  ,  ERROR_INFO  ,  BILLABLE_CHG_ID  ,  PER_ID_NBR  ,  CIS_DIVISION  ,  SA_TYPE_CD  ,
START_DT  ,  END_DT  ,  BILL_PERIOD_CD  ,  PRICEITEM_CD  ,  SQI_CD  ,  SVC_QTY  ,  CHG_TYPE_CD  ,
BILL_AFTER_DT  ,  ADHOC_SW  ,  CHARGE_AMT  ,  CURRENCY_CD  ,  FAST_PAY_VAL  ,  CASE_IDENTIFIER  ,
PAY_NARRATIVE  ,  IS_IND_FLG  ,  REL_RESERVE_FLG  ,  REL_WAF_FLG  ,  EVENT_ID  ,  SQI_CD_RECR  ,
RECR_RATE  ,  RECR_IDFR  ,  CAN_FLG  ,  ILM_DT  ,  ILM_ARCH_SW  ,  DEBT_DT  ,  SOURCE_TYPE  ,  SOURCE_ID)
values
('00000000003346',CAST('29-MAY-20' AS DATE),'UPLD       ',null,0,
0,' ','            ','PO4000123151    ','00001','CHBK    ',
CAST('29-MAY-19' AS DATE),CAST('30-MAY-19' AS DATE),'WPDY    ','MREC0002  ','NUMBER  ',1,'    ',
CAST('29-OCT-20' AS DATE),'N',50,'GBP','Y',null,
'N','N','N','N','N',null,
null,null,'N',CAST('28-MAY-20' AS DATE),'N',null,'chrg','100508927')